version: '3.8'

services:
  app:
    image: ngyuki/php-dev:7.3
    init: true
    ports:
      - 9876:9876
    volumes:
      - .:/code
    working_dir: /code
    environment:
      HOME: /tmp/code
    command: >
      php -S 0.0.0.0:9876 -t ./public
        -d error_reporting=-1
        -d display_errors=on
        -d display_startup_errors=on
        -d log_errors=on
        -d error_log=
        -d zend.assertions=1
        -d assert.exception=1
        -d zend_extension=xdebug.so
        -d xdebug.cli_color=1
        -d xdebug.mode=develop,debug
        -d xdebug.client_host=host.docker.internal
        -d date.timezone=Asia/Tokyo
