<?php $this->layout('Layout/no-login') ?>

<form method="post">
    <label>
        <input type="text" name="username" value="<?= $this->h($username ?? "") ?>" placeholder="username" required>
    </label>
    <label>
        <input type="password" name="password" value="" placeholder="password" required>
    </label>
    <label>
        <button type="submit">Login</button>
    </label>
    <?php if (isset($errors)): foreach ($errors as $error): ?>
    <div>
        <p><?= $this->h($error) ?></p>
    </div>
    <?php endforeach; endif; ?>

</form>
