<?php $this->layout('Layout/layout') ?>

<div class="list-group">
    <a class="list-group-item" href="/user/hoge">/user/hoge</a>
    <a class="list-group-item" href="/attr">/attr</a>
    <a class="list-group-item" href="/relative">/relative</a>
    <a class="list-group-item" href="/response">/response</a>
    <a class="list-group-item" href="/callable">/callable</a>
    <a class="list-group-item" href="/callback">/callback</a>
    <a class="list-group-item" href="/error">/error</a>
    <a class="list-group-item" href="/notfound">/notfound</a>
</div>
